### ISSUE TITLE
When using arabic version on mobile, the menu should open from the right

### ISSUE THREAD

**Issue by yoannfleurydev** [BearStudio/start-ui-web#108]
At the moment, the menu is opening from the left (and the close icon is on the left).

https://user-images.githubusercontent.com/3920615/136712406-840e8a23-1877-4018-9cd1-b8ec3d1a0012.mp4

The menu should open from the right and the close icon should be on top of the “hamburger” menu icon for better UI ergonomics.

**Comment by artfuldev** [comment]
Hi!

Is there a way to identify RTL setups right now that can be quickly used to change the behavior of the hamburger menu?
Do we also aim to add/change documentation?
Will working on this also entail adding tests for the same?

**Comment by artfuldev** [comment]
> the close icon should be on top of the “hamburger” menu icon for better UI ergonomics

I'm not sure I understand this. If we follow RTL semantics, in an RTL setup, the close icon will end up being on the left. Are we attempting to do something different here?

**Comment by yoannfleurydev** [comment]
That's fine, I didn't check the LTR version and made the assumption that the close icon was on top of the hamburger menu icon but that was only a memory from another website. That's my bad and you did great to check the LTR version before and implement like it was just the reverse.

Thanks a lot, I'm reviewing the PR at the moment, and that's exactly what the issue needed.

🤩
