### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by ivan-dalmet** [BearStudio/start-ui-web#113]
Need to update the favicon and mobile icons.

- Web app with 
![image](https://user-images.githubusercontent.com/9749061/138274707-09101548-ef64-4772-afb5-4bcae6e3a0a9.png)
- Storybook with 
![image](https://user-images.githubusercontent.com/9749061/138274680-953afe5f-816b-407e-9bf6-f56f77272d5a.png)

You can use [RealFaviconGenerator](https://realfavicongenerator.net/)

**Comment by SachinHatikankar100** [comment]
Hi @ivan-dalmet can you help me with the file path in which favicons and mobile icons need to be updated. Would like to do some contribution :)

**Comment by anjaligoswami** [comment]
Could you please assign me this issue?
I want to contribute.

**Comment by yoannfleurydev** [comment]
Hi @anjaligoswami any news on this issue ?
