### ISSUE TITLE
Update React Router DOM to v6

### ISSUE THREAD

**Issue by yoannfleurydev** [BearStudio/start-ui-web#133]
Try to update `react-router-dom` to the v6. Check if the basename is supported.

https://reactrouter.com/

**Comment by ivan-dalmet** [comment]
![Just do it](https://media4.giphy.com/media/GcSqyYa2aF8dy/giphy.gif?cid=ecf05e47j7v6qr6qevxrr1juhtkyhbjekkzmc4jxcy4xxyae&rid=giphy.gif)

**Comment by yoannfleurydev** [comment]
Done in #134
