### ISSUE TITLE
It seems that date selector is not translated

### ISSUE THREAD

**Issue by yoannfleurydev** [BearStudio/start-ui-web#139]
It seems that date selector is not translated (Day Picker is fine) 
[Screenshot_20220103_072417_com.android.chrome.jpg](https://user-images.githubusercontent.com/9749061/147904162-6ae8e5d7-ee08-4951-b36a-39c275d01b65.jpg)
(not related to this PR)

_Originally posted by @ivan-dalmet in https://github.com/BearStudio/start-ui-web/issues/138#issuecomment-1003893048_

**Comment by charlelisefouasse** [comment]
Can I be assigned to this issue ?
