### ISSUE TITLE
some part of UI could not be translated correctly by  `DEFAULT_LANGUAGE_KEY` 

### ISSUE THREAD

**Issue by winner106** [BearStudio/start-ui-web#142]
Hello, I downloaded the project to the local, I tried to change `DEFAULT_LANGUAGE_KEY` to `fr` and then  `yarn dev` run the project. 

Everything is fine, but I found that the language of part of the interface could not be translated correctly, as shown in the picture below:

![image](https://user-images.githubusercontent.com/50519642/149613786-2f5771b1-0191-47cb-8565-41bbd991231f.png)

But if I switch languages in `My Account`, all the translations work great!

**Comment by yoannfleurydev** [comment]
This is working as expected. We do not want to override the users language. Here is a demo of the interface with multiple cases.

1. I am not connected, the interface is using the default language (`fr`)
2. I am connect, the interface is using the language of my account (`en`)
3. I change the language of my account, the interface is using it ✅ (`fr`)
4. I log out of the application, I update the default language, the interface updates itself accordingly ✅ (`en`).

https://user-images.githubusercontent.com/3920615/149654885-f79982f8-fa51-4d50-851a-f46f09ea0254.mp4

The language is a user choice, we should not override it based on a default configuration in the code.

I hope everything is clear.
