### ISSUE TITLE
Unable to run jest or storybook when installing swiper.js 

### ISSUE THREAD

**Issue by omar-bear** [BearStudio/start-ui-web#144]
## Description

there is a problem when installing the "[swiper](https://swiperjs.com/)" lib the following utils no longer work:
`jest test` and `storybook` execution

![image](https://user-images.githubusercontent.com/80390318/150135219-c35b215b-8d8e-4e4f-b9b9-87b5a8bcabc1.png)

**Comment by yoannfleurydev** [comment]
This is not a problem with Start UI itself, but with the tools that Start UI is using. They are not ready for ESM. To be honest, this issue will be worked on by frequently updating the libs and tools Start UI is using.

**Comment by yoannfleurydev** [comment]
Closing this issue as not planned. Not a Start UI issue itself.
