### ISSUE TITLE
Add a social block on the login page

### ISSUE THREAD

**Issue by yoannfleurydev** [BearStudio/start-ui-web#212]
Add a text block that is easy to remove to tell users/developers to follow, like Start UI and BearStudio and socials networks.

**Comment by Malek-khannoussi** [comment]
I would like to work on this issue.

**Comment by yoannfleurydev** [comment]
> I would like to work on this issue.

Sure, I've assigned you to that issue.

**Comment by yoannfleurydev** [comment]
I do think that it should contain the following links:

- [ ] https://twitter.com/startui_
- [ ] https://start-ui.com (this one will host a landing page soon)
- [ ] https://github.com/BearStudio
- [ ] https://www.bearstudio.fr/en/

**Comment by yoannfleurydev** [comment]
Closing this issue. We internally discussed about it and want to leave socials as it is now.
