### ISSUE TITLE
Fix forget password link in login interceptor modal

### ISSUE THREAD

**Issue by Rileran** [BearStudio/start-ui-web#215]
## Description

In the login modal shown when the auth token is expired, the button "Forget Password?" does not work.

## How to reproduce

1. Login as any user.
2. Delete the `authToken` for your local storage
3. Click on the "Forget Password?" button in the modal.

https://user-images.githubusercontent.com/38964092/165505466-9e737322-147d-4b8d-972f-fd5e160b893c.mp4

## Cause

The bug comes from the migration to react-router v6 ([commit](https://github.com/BearStudio/start-ui-web/commit/a18a333b411444a4078853e89375f5a77aa47c2a)).

The section causing the bug is the `On Route Change` not triggering when the route changes.

```
  // On Route Change
  useEffect(() => {
    if (isOpen && pathname !== pathnameRef.current) {
      updateToken(null);
      onClose();
    }
  }, [isOpen, updateToken, onClose, pathname]);
```

## Useful links

Prevent navigation in react router v6: https://github.com/remix-run/react-router/issues/8139

**Comment by FlorianGille** [comment]
Hi 👋
I take this issue if it's good for you 😀

**Comment by joaoflaviosantos** [comment]
> Hi 👋 I take this issue if it's good for you 😀

@FlorianGille  Do you already have a solution to this bug?

**Comment by FlorianGille** [comment]
Hi @joaoflaviosantos!
Not yet, I have not had much time in the last few days/weeks but I'll try to find a solution to this issue soon! (I hope this week)

Don't hesitate if you have any ideas 🙂

**Comment by FlorianGille** [comment]
Hello :wave:

I prefer to unassign myself from this issue instead of keeping myself on it. If someone want to take it, feel free to do! :slightly_smiling_face:
