### ISSUE TITLE
Upgrade to react-day-picker 8.X.X

### ISSUE THREAD

**Issue by Jessy-BAER** [BearStudio/start-ui-web#219]
A new version of react-day-picker is available since march 

Read the [Release V8](https://github.com/gpbl/react-day-picker/releases/tag/v8.0.0) and manage the breaking changes

**Comment by yoannfleurydev** [comment]
Maybe change the lib is also a good thing. Just saw this tweet:

https://twitter.com/devongovett/status/1539269528512647171?t=rp-JfBruOG5LS1t1Cz2_Hw&s=19

**Comment by yoannfleurydev** [comment]
This has been done thanks to @DecampsRenan
