### ISSUE TITLE
Upgrade to react-query 4.X.X 

### ISSUE THREAD

**Issue by Jessy-BAER** [BearStudio/start-ui-web#253]
Maybe we can work on upgrade of react query to be up to date ? 

See [migrating guide](https://tanstack.com/query/v4/docs/guides/migrating-to-react-query-4) 

**Update**

We must wait for the release https://github.com/TanStack/query/issues/3790#issuecomment-1179431860

**Comment by ivan-dalmet** [comment]
Fix by #260
