### ISSUE TITLE
Fix: CI `test` step on gitlab-ci

### ISSUE THREAD

**Issue by Rileran** [BearStudio/start-ui-web#273]
When deploying start-ui with gitlab-ci, the `test` step will fail because cypress wont' work inside docker (as there is not X server available).

Solution seems to be using image `cypress/base` for this particular step (see https://docs.cypress.io/examples/examples/docker#Images  and https://gitlab.com/cypress-io/cypress-example-docker-gitlab/-/blob/master/.gitlab-ci.yml)

I will test this solution and submit a PR soon.

[error.log](https://github.com/BearStudio/start-ui-web/files/9257800/error.log)

**Comment by Rileran** [comment]
I have got is mostly working in this PR https://github.com/BearStudio/start-ui-web/pull/275, but now some test cases are failing (see https://gitlab.com/thomas338/start-ui-cypress-gitlab-ci/-/jobs/2814226349).

**Comment by FabienEssid** [comment]
I have the same issue, I will try to find a way to fix it
