### ISSUE TITLE
Add auto-animate on DataList

### ISSUE THREAD

**Issue by yoannfleurydev** [BearStudio/start-ui-web#293]
To improve UX (User eXperience), it would be great to have DataList component use auto-animate so we can have smooth animations on addition, deletion of items.

https://auto-animate.formkit.com/

**Comment by Malay-dev** [comment]
Hey, I would like to work on this issue. @yoannfleurydev

**Comment by yoannfleurydev** [comment]
Hi, awesome, I assign you to it.
