### ISSUE TITLE
Add a feature part to the README

### ISSUE THREAD

**Issue by yoannfleurydev** [BearStudio/start-ui-web#299]
At the moment, the README is really centered around technologies. This is fearful for new users. At @BearStudio, we think that it will be better to list feature of the starter instead of technologies, as the features may remain the same even if a technology may change.

Feel free to comment on this issue with a list of features that you find useful or feel free to join our [Discord server](https://go.bearstudio.fr/discord) to answer [this discussion](https://discord.com/channels/452798408491663361/1034860472249352262)

**Comment by ivan-dalmet** [comment]
For me, the features that I like in Start UI:
- Chakra UI setup with custom theme (brand color, @primary button, ...) and type generation.
- Basic responsive layout setup (navbar, page)
- Extra common components (like Field*)
- CRUD like example
- Log In / Sign In flow
- ESLint / Prettier / Husky setup
- i18n setup if needed

**Comment by DecampsRenan** [comment]
IMO, features I like:

- Great list of pre-build components
- Already existing Fields ready to use in Forms, with some nice defaults (only show errors after a submit, etc..)
- Routes already setup with guards if needed
- Storybook already setup with a lot of examples
- Admin view (but I think we should make it more agnostic, it is really tied to JHipster right now)
- Sign in / Sign up flow
- i18n already setup
- Many examples for making requests, customizing chakra ui theme, page layout
- Really easy to build and deploy

**Comment by HugoPerard** [comment]
The features that I find useful :
- Config (ts, linter, translation, etc...), juste have to focus on app development
- Routing setup
- Most commons components already 
- Required app screens (login, account, admin, etc..)
- Basic theme setup, easily customizable
