### ISSUE TITLE
husky - pre-commit hook exited with code 1 (error)

### ISSUE THREAD

**Issue by winner106** [BearStudio/start-ui-web#333]
```js
VS Code Version: 1.74.3 (user setup)
Node.js: 16.14.2
OS: Windows_NT x64 10.0.22621
```

when I use `npx create-start-ui@latest --web myApp` created a new project, then I tried to  commit with `init` in VS Code(I haven't changed any code), but got error as follow:  

![image](https://user-images.githubusercontent.com/50519642/213490414-352fea8c-2fac-4617-9b08-29c7f51e296b.png)

Could you please give me some guidance? Thanks a lot!

**Comment by ivan-dalmet** [comment]
Can you share the Git log here? :)

**Comment by ivan-dalmet** [comment]
Ok I've reproduce the issue. We will fix that :) Thanks for the issue
![image](https://user-images.githubusercontent.com/9749061/213510922-6e09d89c-de65-4ab4-acac-78840579a73c.png)

**Comment by ivan-dalmet** [comment]
We should have a eslintignore file to prevent this @DecampsRenan is on it. A fix should be available tomorrow 😊

**Comment by DecampsRenan** [comment]
Hello @winner106 ! We merged the fix for your issue

You can now re-create a new project, it should works as expected this time 😉 
If you want to apply the fix by yourself, you can update these two files: https://github.com/BearStudio/start-ui-web/pull/334/files

Thanks for reporting this issue !

**Comment by winner106** [comment]
> Hello @winner106 ! We merged the fix for your issue
> 
> You can now re-create a new project, it should works as expected this time 😉 If you want to apply the fix by yourself, you can update these two files: https://github.com/BearStudio/start-ui-web/pull/334/files
> 
> Thanks for reporting this issue !

The problem has been solved, very grateful 🆒
