### ISSUE TITLE
Direct navigation to admin route shows blank UI when not logged in

### ISSUE THREAD

**Issue by vmundhra** [BearStudio/start-ui-web#340]
When trying to navigate directly to admin route inside app by copy pasting the URL, the UI shows blank white screen. Visit the following link https://demo.start-ui.com/app/admin and make sure the user is signed out. the dashboard route works and the login screen is shown with a redirect in URL. But this does not work for admin routes.

**Comment by HugoPerard** [comment]
Thanks for your feedback, I successfully reproduce the bug. We will try to fix it as soon as possible

**Comment by NiazMorshed2007** [comment]
@HugoPerard is this open?

**Comment by HugoPerard** [comment]
Not yet sorry
If nobody fix it, I will try to do it as soon as possible, but feel free to contribute if you want

**Comment by HugoPerard** [comment]
@vmundhra @NiazMorshed2007 I just open an PR with a fix, you can take a look : https://github.com/BearStudio/start-ui-web/pull/343
