### ISSUE TITLE
Check for `useColorModeValue` usage

### ISSUE THREAD

**Issue by yoannfleurydev** [BearStudio/start-ui-web#370]
As `_dark` is implemented in Chakra UI, we do not need `useColorModeValue` anymore for most of its implementation.

Check for source code using it and refactor to use `_dark`

**Comment by souravghosh01** [comment]
I want to contribute! can you assign it to me?

**Comment by yoannfleurydev** [comment]
@souravghosh01 Sure, I assign to this issue.

**Comment by tarunsamanta2k20** [comment]
@yoannfleurydev I'd like to work on it.

**Comment by gracebir** [comment]
> @souravghosh01 are you still working on it?
> 
> @tarunsamanta2k20 feel free to submit a PR.

@yoannfleurydev , I have worked on it, and there is an open PR
