### ISSUE TITLE
bug: Toploader loads endlessly on CMD + click

### ISSUE THREAD

**Issue by tomcru** [BearStudio/start-ui-web#434]
Toploader triggers on external link clicks & loads endlessly on CMD + click

I can PR this issue, I would replace the current package with a drop-in replacement & a much more up-to-date library: [Holy Loader](https://github.com/tomcru/holy-loader) (this is my library) - keeping the original look 1:1, but removing the bugs.

`nextjs-toploader` doesn't look like it is being maintained anymore.

**Comment by yoannfleurydev** [comment]
Hey @tomcru, thanks for raising the issue.

I can totally reproduce the infinity load on the admin interface by <kbd>CMD + Click</kbd>

That could be great if we have a 1:1 replacement. PR is welcome!
