### ISSUE TITLE
Warning: Extra attributes from the server: class

### ISSUE THREAD

**Issue by winner106** [BearStudio/start-ui-web#441]
When I tried to use the latest version today, after installing the dependencies and starting the project, I found an error message in the browser console.

![image](https://github.com/BearStudio/start-ui-web/assets/50519642/51320587-a25a-4600-a18c-969c3cefa3c3)

**Comment by yoannfleurydev** [comment]
Hey @winner106 , thanks for raising the issue, it's an issue with Chakra UI

https://github.com/chakra-ui/chakra-ui/issues/7040

**Comment by winner106** [comment]
Thanks for the information, I temporarily solved it like this:

![image](https://github.com/BearStudio/start-ui-web/assets/50519642/05705658-cd0c-48da-89fb-3fb38937e8fb)

**Comment by yoannfleurydev** [comment]
I'm closing this issue as it is not a 🚀 Start UI [web] issue, but we will upgrade Chakra UI once it is done.
