### ISSUE TITLE
Translation Error in New Account Email (Arabic)

### ISSUE THREAD

**Issue by khannoussi-malek** [BearStudio/start-ui-web#448]
**Title:** Translation Error in New Account Email (Arabic)

**Problem Description:**

- Briefly explain the incorrect translation in the new user email.

- **Example**: "The Arabic greeting 'مرحبًا {{اسم}}،' is not rendering correctly. The placeholder '{{اسم}}' is not being replaced with the user's name."

![image](https://github.com/BearStudio/start-ui-web/assets/61156745/a212b880-21da-47e2-8e8e-cb0e419cad2d)

**Steps to Reproduce:**

1. Create a new user account and enter an Arabic name.
2. Check the welcome email.

**Expected Behavior:**

The greeting should read 'مرحبًا [username]،' with the placeholder replaced by the correct name.

**Comment by khannoussi-malek** [comment]
After reviewing the code, I found that there is another translation probably having the same problem (logically).

The list of files that have the same problem:

- `src/locales/ar/emails.json`

![image](https://github.com/BearStudio/start-ui-web/assets/61156745/03725446-03db-46b1-a54b-c5903a24c7fc)

- `src/locales/ar/users.json`

![image](https://github.com/BearStudio/start-ui-web/assets/61156745/99c85f47-a34e-458e-b774-06569bd1f7a8)


**I would like to address this issue.**

**Comment by ivan-dalmet** [comment]
Thanks @khannoussi-malek. Feel free to open a PR on this, we will be happy about your contribution ☺️

**Comment by yoannfleurydev** [comment]
closed with #449
