### ISSUE TITLE
Icon generation not working

### ISSUE THREAD

**Issue by ivan-dalmet** [BearStudio/start-ui-web#460]
The following command is not working since the v2 version
```
pnpm  theme:generate-icons
```

![image](https://github.com/BearStudio/start-ui-web/assets/9749061/82e51565-7246-48fc-b51b-4e346ee88b5d)

**Comment by DecampsRenan** [comment]
It seems to be an issue with prettier formatting, it seem to use "flow" as the parser (which I suppose do not handle correctly this kind of imports)

I'll check to see how to override this behavior (I think we can specify a custom parser, maybe we can do it for generated icons files)

**Comment by DecampsRenan** [comment]
I think it is linked to this issue: https://github.com/gregberge/svgr/issues/893
I will do a PR to fix it, I will disable prettier formatting from svgr since it will still be done with lint-staged
