### ISSUE TITLE
Cleaner React-Hook-Form implementation 

### ISSUE THREAD

**Issue by ntatoud** [BearStudio/start-ui-web#475]
## In the Form and Fields components declaration, wouldn't it be better to : 
- Use import type instead of import when possible. Cf:  
![image](https://github.com/BearStudio/start-ui-web/assets/135032615/dde8ceb5-3cc8-4dc2-973f-668a82249f73)

## Remove the control props from FormFields in Forms.

Because the fields are used in a FormProvider context, there is no need to pass the `control` prop to the FormField component
Exemple : 
```
  <Form {...form} onSubmit={onSubmit}>
      <Stack spacing={4}>
        <FormField
          size="lg"
          type="text"
          name="email"
          control={form.control} ❌ Not needed
          label="Email"
        />
        <FormField
          size="lg"
          type="password"
          name="password"
          control={form.control} ❌ Not needed
          label="Password"
        />

        <HStack justify="end">
          <Button
            type="submit"
            variant="@primary"
            isLoading={login.isPending}
            justifySelf="end"
          >
            Login
          </Button>
        </HStack>
      </Stack>
    </Form>
```

**Comment by ivan-dalmet** [comment]
The control props is needed for typesafety ;)
