### ISSUE TITLE
ConfirmMenuItem style different from MenuItem

### ISSUE THREAD

**Issue by yoannfleurydev** [BearStudio/start-ui-web#66]
Here is a video demo of the `ConfirmMenuItem` component. When disabled, the **Supprimer** `ConfirmMenuItem` is different from the other `MenuItem`.

https://user-images.githubusercontent.com/3920615/121869467-5d11ac00-cd02-11eb-8c3d-7f9b2c69b50f.mp4

**Comment by Selharem** [comment]
Can I take this one !

**Comment by yoannfleurydev** [comment]
> Ok @yoannfleurydev, thanks!

Any news ?

**Comment by ImbuPro** [comment]
Hey, the issue fixed, watch this :
- https://user-images.githubusercontent.com/71929996/146028002-b7de7cef-66e4-45e2-8aa1-3633be192bd2.mov


- https://user-images.githubusercontent.com/71929996/146028023-a7a221c1-cd0f-40f0-a248-46f83ed38c3e.mov

**Comment by yoannfleurydev** [comment]
Hi @ImbuPro, thanks for your time. This seems to be fixed, probably by a Chakra UI update as we didn't change anything for this. I close this issue.
