### ISSUE TITLE
Change hard coded strings to Enum const for routing and API error keys

### ISSUE THREAD

**Issue by medamineziraoui** [BearStudio/start-ui-web#79]
Replace hard coded string with constants
https://github.com/BearStudio/start-ui/pull/78#discussion_r680941499
https://github.com/BearStudio/start-ui/pull/78#discussion_r680941587

**Comment by Patil2099** [comment]
I would love to work on it.

**Comment by ivan-dalmet** [comment]
https://github.com/BearStudio/start-ui-web/pull/80#pullrequestreview-722086423
