### ISSUE TITLE
FieldCheckboxes doesn't work with object values

### ISSUE THREAD

**Issue by Rileran** [BearStudio/start-ui-web#85]
## Description

The component `FieldCheckboxes` doesn't work with object values in options.

Is that a normal behavior ? Maybe the value should only be a string but that would limit the usefulness of the FieldCheckboxes component.

## Example

In this example, the checkbox won't change their state if you click on them.

![withNestedValues](https://user-images.githubusercontent.com/38964092/128217378-3e526eef-c28a-48c5-98a2-0c6e5de28b46.gif)

```jsx
export const WithNestedValues = () => {
  const options = [
    { value: {firstName: 'Alice', age: 22}, label: 'Alice' },
    { value: {firstName: 'Bob', age: 23}, label: 'Bob' }
  ];

  return (
    <Formiz>
      <FieldCheckboxes
        name="FieldCheckboxes"
        label="Label"
        helper="Helper"
        options={options}
      />
    </Formiz>
  );
};
```

**Comment by ivan-dalmet** [comment]
Fixed by #93
